# Generated by Django 3.2 on 2021-04-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.CharField(max_length=30, verbose_name='发送方')),
                ('recive', models.CharField(max_length=20, verbose_name='接收方')),
                ('msgtype', models.CharField(max_length=20, verbose_name='发送内容类型')),
                ('content', models.CharField(max_length=500, verbose_name='发送的内容')),
                ('msgtime', models.CharField(max_length=50, verbose_name='发送时间戳')),
            ],
            options={
                'verbose_name_plural': '聊天表',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='客户姓名')),
                ('health', models.CharField(max_length=200, verbose_name='所属健康师')),
            ],
            options={
                'verbose_name_plural': '客户表',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='健康师姓名')),
                ('Customer_list', models.CharField(max_length=200, verbose_name='负责的客户列表')),
            ],
            options={
                'verbose_name_plural': '健康师表',
            },
        ),
    ]
