# Generated by Django 3.2 on 2021-04-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='seq',
            field=models.IntegerField(default=0, verbose_name='seq值'),
        ),
    ]
